# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LetsPlayStoryboards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'AudioKit', '~> 4.7'

  # Pods for LetsPlayStoryboards

  target 'LetsPlayStoryboardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LetsPlayStoryboardsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
